### ISSUE TITLE
Show network ID in history

### ISSUE THREAD

**Issue by edmundedgar** [LimeChain/etherlime#113]
`etherlime history` is a really handy way to look back later and check what you deployed and which address it went to.

It would be useful if it showed the network ID, so you could see what you deployed to which network.

**Comment by Perseverance** [comment]
Hey @edmundedgar Awesome idea. Will implement that shortly :). Anything else that you feel might be improved or done better?

**Comment by Perseverance** [comment]
Implemented in 1.0.0
