### ISSUE TITLE
[ETHERLIME-TEST] Have not access to mocha timeout functionality 

### ISSUE THREAD

**Issue by bakasura980** [LimeChain/etherlime#122]
Some of my tests need more than 2000ms to execute. I should have a way to increase the mocha default time.

Hint: In etherlime-test.js attach `mocha` to the `global` object and in tests, access timeout function as follow:
`mocha.timeout(YOUR TIME)`

**Comment by NikolayAngelov** [comment]
Hello bakasura980,
It is already possible to access the ```mocha``` instance inside your tests via ```this```, but you need to make sure that you are not using ```arrow``` function as they change the ```this``` reference.
Example:
```
it('Example Test', function() {
     this.timeout(5000);
});
```
In case you are using normal function ()  { } declaration the ```this``` will be pointing to the **mocha** and you will be able to set your desired ```timeout```

Note: This can be done in ```Describe``` as well to set the timeout for multiple tests that rune the same ```Suite```

In case we want to introduce such functionality to **Etherelime** I think the best approach will be to have it as an optional parameter to the ```etherlime test``` (Example: ```etherlime test --timeout=10000```)
Till then I hope that you will be able to have the workaround that I explained early.
