### ISSUE TITLE
`etherlime deploy` fails with Error: invalid sender

### ISSUE THREAD

**Issue by saitam1** [LimeChain/etherlime#136]
I am trying to deploy a contract with `etherlime` to a private permissioned `Quorum` network:

`etherlime init    --> OK`

`etherlime compile --> OK`

`etherlime deploy  --> Error`

Error:

```
Compilation finished successfully
Deployer set to deploy from address: 0xC58A28d310c76e8298FA456381E6F2da9F046V54

JSONRPC Deployer Network: http://localhost:22000/

Deploying contract: LimeFactory
{ Error: invalid sender ...
```
But the sender is actually valid! The address was derived from the `privateKey` I have passed to `JSONRPCPrivateKeyDeployer` and it is listed in `personal.listAccounts` when I make the check in the geth console, so what could be wrong?

**Comment by Perseverance** [comment]
Can you show us the deploy script (you can edit sensitive data)?

**Comment by saitam1** [comment]
```
const etherlime = require('etherlime');
const LimeFactory = require('../build/LimeFactory.json');

const defaultConfigs = {
    gasPrice: 0,
    gasLimit: 4700000
}

const deploy = async (network, secret) => {

	const deployer = new etherlime.JSONRPCPrivateKeyDeployer('0xb87129acf30c....', 'http://localhost:22000/', defaultConfigs);
	const result = await deployer.deploy(LimeFactory);

};

module.exports = {
	deploy
};

```

**Comment by ochikov** [comment]
@saitam1 
Hello,
Can you try to omit the 'defaultConfigs' parameter from the 'JSONRPCPrivateKeyDeployer' and paste your results here.

Thank you.

**Comment by saitam1** [comment]
Thank you for the offer, I will gladly accept it later, cause I am on my way right now.
I have tried to deploy without ` defaultConfigs` but still have the same error. Does it help if I post the whole error message here? I will wipe out the chain data anyway later:
```

{ Error: invalid sender
    at getResult (/home/username/etherlime/node_modules/ethers/providers/json-rpc-provider.js:40:21)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/username/etherlime/node_modules/ethers/utils/web.js:111:30)
    at exports.XMLHttpRequest.dispatchEvent (/home/username/etherlime/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/username/etherlime/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/username/etherlime/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: -32000,
  data: undefined,
  url: 'http://localhost:22000/',
  body:
   '{"method":"eth_sendRawTransaction","params":["0xf905d7018083..."],"id":42,"jsonrpc":"2.0"}',
  responseText:
   '{"jsonrpc":"2.0","id":42,"error":{"code":-32000,"message":"invalid sender"}}\n',
  transaction:
   { nonce: 1,
     gasPrice: BigNumber { _hex: '0x00' },
     gasLimit: BigNumber { _hex: '0x05ec1a' },
     to: null,
     value: BigNumber { _hex: '0x00' },
     data:
      '0x608060405234...',
     chainId: 1337,
     v: 2709,
     r:
      '0x6dba56dd4397fc2aaffc1b6b1fb920d9aa99a3aec23eb3a2c7cdb4cc344e19a9',
     s:
      '0x2f52686086247bf1bbbbb3289108a673fde1a8cf22eb322e7782b5bec71b8065',
     from: '0xC58A28d310c76e8298FA456381E6F2da9F046V54',
     hash:
      '0x28e5137b820f7432e94ae85d6d9119485ede98d9f3b6b84a69f49a599e2cf1e9' },
  transactionHash:
   '0x28e5137b820f7432e94ae85d6d9119485ede98d9f3b6b84a69f49a599e2cf1e9' }
Your deployment script finished with failure!
```

**Comment by ochikov** [comment]
@saitam1 
Can you verify that you pass on JSONRPCPrivateKeyDeployer, the private key, not the address of the account ?

**Comment by saitam1** [comment]
I am getting it via `web3.eth.accounts.decrypt` from the JSON keystore file. Just checked it once again, I am passing the private key, not the address

**Comment by saitam1** [comment]
In the error message I see `"id":42`, this is actually the kovan network. Is there a way to pass the network id? I tried ´network_id: "*"` like in truffle, but it didn't work

**Comment by ochikov** [comment]
@saitam1 In the current version of Etherlime we support providing a nodeUrl. 
Can you try something, so we can be sure that your installed version of etherlime works:
1. Run etherlime ganache
2. Use one of the 10th private keys and try to deploy using the default local node that etherlime ganache expose on 'http://localhost:8545/'

If you are able to deploy there, we will continue to find solution for your private Quorum network.

**Comment by saitam1** [comment]
worked:

```
Compilation finished successfully
Deployer set to deploy from address: 0xD9995BAE12FEe327256FFec1e3184d492bD94C31

JSONRPC Deployer Network: http://localhost:8545/

Deploying contract: LimeFactory
Waiting for transaction to be included in a block and mined: 0x3f50e985436e100568259211a96538df74449ac5fd202e8d5082e492b55992b2
Contract LimeFactory deployed at address: 0xc9707E1e496C12f1Fa83AFbbA8735DA697cdBf64
Your deployment script finished successfully!

Here is your report:
┌───────────────┬────────────────────────────────────────────────────────────────────┐
│ Event Time    │ 7 Jan, 11:01:44                                                    │
├───────────────┼────────────────────────────────────────────────────────────────────┤
│ Executor      │ JSONRPCPrivateKeyDeployer                                          │
├───────────────┼────────────────────────────────────────────────────────────────────┤
│ Name or Label │ LimeFactory                                                        │
├───────────────┼────────────────────────────────────────────────────────────────────┤
│ Tx Hash       │ 0x3f50e985436e100568259211a96538df74449ac5fd202e8d5082e492b55992b2 │
├───────────────┼────────────────────────────────────────────────────────────────────┤
│ Status        │ Success                                                            │
├───────────────┼────────────────────────────────────────────────────────────────────┤
│ Gas Price     │ 2.0 Gwei                                                           │
├───────────────┼────────────────────────────────────────────────────────────────────┤
│ Gas Used      │ 420122                                                             │
├───────────────┼────────────────────────────────────────────────────────────────────┤
│ Result        │ 0xc9707E1e496C12f1Fa83AFbbA8735DA697cdBf64                         │
└───────────────┴────────────────────────────────────────────────────────────────────┘

```

**Comment by ochikov** [comment]
@saitam1 I think that the problem comes from how ethers.js is interacting with Quorum network. Can you test the following thing:
Can you modify the 'defaultConfigs' to look like this and then pass it ot the 'JSONRPCPrivateKeyDeployer':

const defaultConfigs = {
		gasPrice: 0,
		gasLimit: 4700000,
		chainId: 0
	}

**Comment by saitam1** [comment]
Still getting the same error `Error: invalid sender`

**Comment by saitam1** [comment]
Quorum and Ethereum have a few differences. For example: 

- If you use `web3.eth.sendTransaction(transactionObject [, callback])` and if the transaction was a contract creation you have to use `web3.eth.getTransactionReceipt()` to get the contract address, after the transaction was mined. In Ethereum you don't have to do this. 
- With `raft` consensus some people have the problem that `truffle` gets "stuck". And the reason might be that its waiting for additional blocks to confirm the txn. A way to fix it is sending an unrelated txn through the node, which will allow truffle to proceed.

Might any of these points be related to Etherlime?

**Comment by ochikov** [comment]
@saitam1 Hello,
We have new version of etherlime -> 0.10.4. In this version we added the possibility to set `chainId` parameter in order to manually set the chainId of the node. With this functionality we managed to deploy a simple smart contract on Quorum network with custom provided `chainId`. Thank you for the opened issue and for provided help solving it!

**Comment by Perseverance** [comment]
@saitam1 has this been resolved? Can I close it?
