### ISSUE TITLE
Add option for etherlime compile to create .abi files containing only the abi

### ISSUE THREAD

**Issue by Perseverance** [LimeChain/etherlime#142]
When I am developing in non-js language, sometimes I need only the abi and have to do a lot of manual work in order to get it. Add option to etherlime compile to generate me .abi files in addition to the .json files in order to use them fast and easy

**Comment by ochikov** [comment]
This is already included in version 1.2.0. More about this option here: https://etherlime.readthedocs.io/en/latest/cli/compiling.html
