### ISSUE TITLE
Increase Test Timeouts

### ISSUE THREAD

**Issue by fredfortier** [LimeChain/etherlime#195]
I'm trying to increase the test timeouts but the mocha method `this.timeout(5000)` does not work. Any suggestions?

**Comment by desimira** [comment]
`this.timeout()` doesn't work in arrow function, i.e. you need to write
```
it('should do something', function () {
     this.timeout()
})
```
If this is not the case, can you give us some code example.

**Comment by ochikov** [comment]
Etherlime 1.1.1 gives possibility to pass ```timeout```  as optional parameter of running mocha tests. Please refer to: https://etherlime.readthedocs.io/en/latest/cli/test.html
