### ISSUE TITLE
Missing mocha dependency

### ISSUE THREAD

**Issue by montyly** [LimeChain/etherlime#225]
Hi,

From a fresh installation, I have this issue with the 2.0.0 release:
```
$ npm install etherlime
$ etherlime init
Error: Cannot find module 'mocha' 
```

`mocha` was present in the dependencies for 1.2.0 (https://www.npmjs.com/package/etherlime/v/1.2.0), but is not anymore in 2.0.0 (https://www.npmjs.com/package/etherlime/v/2.0.0). 

The script is [this one](https://github.com/crytic/slither/blob/master/scripts/travis_test_etherlime.sh#L13-L14), and the full error log is [here](https://travis-ci.org/crytic/slither/jobs/535441698). The failing mocha invocation is:

https://github.com/LimeChain/etherlime/blob/747fd48d550a6cf1d96b93e61d6e7b797be6cdb3/packages/etherlime/cli-commands/etherlime-test/etherlime-test.js#L1

Is it an issue on my side? 

Thanks!

**Comment by ochikov** [comment]
Hello @montyly, the issue is on our side. Thank you for reporting it. We are working to resolve it.

**Comment by ochikov** [comment]
Hello @montyly Etherlime v2.0.1 was released fixing the issue.

**Comment by montyly** [comment]
Great, thanks for the quick fix!

**Comment by ochikov** [comment]
You are welcome!
