### ISSUE TITLE
Reset Ganache timestamp

### ISSUE THREAD

**Issue by javaadpatel** [LimeChain/etherlime#233]
Hi,

I'm writing some unit tests and one of them moves the ganache provider ahead a number of seconds using:
`var secondsMargin = 900; //this margin is because miners can edit the timestamp by 900 seconds
        var timeTravelSecondsRequired = parseInt(
            moment.duration(
                moment.unix(investmentDetails.deadline).diff(moment())
                ).asSeconds()
                ) + secondsMargin;
        utils.timeTravel(provider, timeTravelSecondsRequired);`

but then other tests which are supposed to be independent now have the ganache provider fast-forwarded. Is there any way to reset the blocktime without restarting ganache? I tried:
`utils.setTimeTo(provider, moment().unix());`
but then get the error:
`Error: cannot decrease time to 1559389955 from 1562019342

**Comment by javaadpatel** [comment]
I have changed my code now to be based on the current ganache block time,  and I am getting the blocktime using:
`function getBlockTimestamp() public view returns (uint){
        return block.timestamp;
    }`

but occasionally, the ganache blocktime comes out insanely high, and when i look at the ganache logs i see "Block Time: Invalid Date": 
![image](https://user-images.githubusercontent.com/22832462/58752662-13571f80-84b3-11e9-9e9c-d0f5d1495469.png)

**Comment by NikolayAngelov** [comment]
Hello @javaadpatel 

I can suggest two different approaches when trying to test with TimeTravel.
First one is having separated deployments of the contract for your test suites. This means that you have different Describes for different kind of tests and where you test time travel you have a separated deployment (describe) which holds all the test that will be in the future. With this way, you usually don't want to return back.

The second way is to tell your Ganache to make a `snapshot`
Snapshot is basicly recording the current state of the Chain and afterward, at any point, you can `revert` to this state. 
It will be something like Save Snapshot -> Do Test/Logic travel to the future -> Assert stuff -> Revert to the Snapshot.
The Snapshot thing was implemented in the previous version of Etherlime but seems to be removed from the current version but you can still use it by sending the Ganache the proper RPC Call.

> **evm_snapshot** : Snapshot the state of the blockchain at the current block. Takes no parameters. Returns the integer id of the snapshot created. A snapshot can only be used once. After a successful evm_revert, the same snapshot id cannot be used again. Consider creating a new snapshot after each evm_revert if you need to revert to the same point multiple times.
**evm_revert** : Revert the state of the blockchain to a previous snapshot. Takes a single parameter, which is the snapshot id to revert to. If no snapshot id is passed it will revert to the latest snapshot. Returns  true.
>

**Comment by javaadpatel** [comment]
I'm leaning towards the second method you described because I would like to write a test where: Investment is made -> Time passes (simulated using timeTravel) -> investment can be withdrawn (because some deadline has been passed).

would it be possible to give an example of the snapshot syntax and how i would implement it in a beforeEach and afterEach block? 

i tried this:

```
beforeEach(async () => {
        deployer = new etherlime.EtherlimeGanacheDeployer(managerAccountSecretKey);
        provider = deployer.provider;
        console.log("saving snapshot");
        utils.snapshot(provider);
        managerWallet = new ethers.Wallet(managerAccountSecretKey, provider);
        investmentFactoryInstance = await deployer.deploy(InvestmentFactory);
    });

    afterEach(async() => {
        console.log("reverting to snapshot");
        utils.revertState(provider);
    });
```


but i am getting the errors:
```
  1) Investment Contract
       "before each" hook for "should be a valid address":
     TypeError: utils.snapshot is not a function
      at Context.beforeEach (test\exampleTest.js:31:15)

  2) Investment Contract
       "after each" hook for "should be a valid address":
     TypeError: utils.revertState is not a function
      at Context.afterEach (test\exampleTest.js:38:15)
```

**Comment by NikolayAngelov** [comment]
Usually what you did should work but from what I see those `utils` functions do not exist in the current Etherlime version. I guess the Team removed them in some of the versions maybe they were not working properly or something.

**Comment by ochikov** [comment]
Hello @javaadpatel & @NikolayAngelov. We are going to add these utils functions in the next release. Sorry for the inconvenience.

**Comment by javaadpatel** [comment]
Hi @ochikov , its all good, really appreciate the library so something this small is not really an issue. I've noticed that I get the "Block Time: Invalid Date" error from etherlime ganache, if i timeTravel too far into the future, so i've just moved all my tests that use timeTravel into a seperate describe block so they are not run everytime but only when i specifically want to test that logic.

for anyone interested, all tests in the describe block can be skipped by using:
``` 
const shouldRunTests = false;
(shouldRunTest ? describe : describe.skip)('Investment Contract (TimeTravel Tests)', () => {
````
