### ISSUE TITLE
Documentation should reflect need to import etherlime-lib and separate npm dependency

### ISSUE THREAD

**Issue by thegostep** [LimeChain/etherlime#250]
Currently, `yarn add etherlime` does not import as a sub dependency etherlime-lib.

However, the examples in the documentation do not reflect the need to add etherlime-lib separately.

**Comment by ochikov** [comment]
Thank you for your feedback. Actually, we provided migration guide and there we included the need of installation of `etherlime-lib`. We are going to improve also the other pages of the documentation.
