### ISSUE TITLE
Vyper compiler not functional on Windows 10 & WSL Ubuntu

### ISSUE THREAD

**Issue by RyRy79261** [LimeChain/etherlime#252]
## Description
When Etherlime attempts to run the `docker run` command to compile Vyper, the console throws an invalid character issue. 

Additionally, when running from a Linux subsystem which has the same pathing syntax as typical unix systems, the console throws an `invalid ELF` issue

**Comment by ochikov** [comment]
@RyRy79261 I think that your problem is already solved ?

**Comment by RyRy79261** [comment]
@ochikov yes in 2.5.7, closing it now
