### ISSUE TITLE
EtherlimeGanacheDeployer should accept ethers provider as parameter

### ISSUE THREAD

**Issue by thegostep** [LimeChain/etherlime#262]
This would allow for running tests without opening local ports. See examples: https://github.com/trufflesuite/ganache-cli#usage

**Comment by thegostep** [comment]
This is not currently possible using coverage

**Comment by ochikov** [comment]
Yes, it is not possible for using it with coverage. I explained why [here](https://github.com/LimeChain/etherlime/issues/269#issuecomment-519084701)
I am closing this issue because of duplication with #269
