### ISSUE TITLE
Add transaction debugger in the etherlime CLI

### ISSUE THREAD

**Issue by Perseverance** [LimeChain/etherlime#27]
# Overview
As a developer I frequently need to debug my failing transactions. I need to have a tool to debug the problems of my transactions

## Changes needed:
TBD

**Comment by BenSchZA** [comment]
We've been using `truffle debug` with their variable inspection alongside Etherlime. Somehow integrating that tool into Etherlime would be great. Although for now using them together works just fine.

**Comment by ochikov** [comment]
Ethereum Transaction debugger is integrated in etherlime in version 1.0.0.
