### ISSUE TITLE
Ignore directories in etherlime coverage

### ISSUE THREAD

**Issue by kenchangh** [LimeChain/etherlime#270]
Currently, the project I'm working on has a lot of OpenZeppelin contracts in the `contracts` directory. This clutters the `etherlime coverage` results.

Would be a good enhancement to ignore these directories of helper contracts that do not affect code coverage.

**Comment by ochikov** [comment]
Thank you for the provided issue. As soon as we fix your issue, we are going to release a new version and I am going to notify you.
