### ISSUE TITLE
Getting injected items for external scripts.

### ISSUE THREAD

**Issue by Jaimeloeuf** [LimeChain/etherlime#292]
When writing tests, we are provided with injected item like "accounts" which allow us to easily do stuff on the test net, etherlime ganache.

However for external scripts where you still want to interact with the same contracts on the same network, I would like to ask how would you be able to get the accounts value?

Currently I am using a method that I think might be some sort of a hack, where I ran a fake test file, get the accounts object, and write it file, before using external scripts read that file to use those accounts.

Thanks in advance!

**Comment by desimira** [comment]
Hi! To access an account, you can instantiate a wallet with `ethers` and pass the privatekey and the provider.
```
const ethers = require('ethers'); 
let wallet = new ethers.Wallet(privateKeyFromGanache, provider);
```
And you should have the account from the privatekey you have provided. Hope it helps! If you have other questions let us know! :)

**Comment by Jaimeloeuf** [comment]
Just tested it and it does create the same format as expected, thanks! But may I know if there are any plans for etherlime to create and inject it into external scripts to use so we do not have to manually get the privateKey and create a wallet object? Because this seems to be slightly tedious when working with alot more accounts for testing, something like the injected accounts variable in etherlime tests would be great if they are available!

Thanks again!
