### ISSUE TITLE
Not installable on Node 12

### ISSUE THREAD

**Issue by timoxley** [LimeChain/etherlime#314]
Not directly this repo's fault but because the deprecated and incompatible `scrypt` is indirectly depended on by `ethereum-transaction-debugger`, it's impossible to install or run etherlime on Node 12. 

Your CI may not have noticed this as the etherlime `.travis.yml` only seems to test Node 8, but note that Node 8 is no longer officially supported, i.e. end of life as of January 2020: https://nodejs.org/en/about/releases/

if `scrypt.js@0.2.0` was `scrypt.js@0.3.0` this problem would go away as 0.3 has a native JS fallback.

```
┬ etherlime@2.3.0
│ └─┬ ethereum-transaction-debugger@0.0.5
│   └─┬ truffle-decode-utils@1.0.4
│     └─┬ web3@1.0.0-beta.37
│       └─┬ web3-eth@1.0.0-beta.37
│         └─┬ web3-eth-accounts@1.0.0-beta.37
│           └─┬ scrypt.js@0.2.0
│             └── scrypt@6.0.3

```

Also note that:

[truffle-decode-utils](https://www.npmjs.com/package/truffle-decode-utils) is deprecated in favour of [@truffle/decode-utils](https://www.npmjs.com/package/@truffle/decode-utils) which is deprecated in favour of [@truffle/decoder](https://www.npmjs.com/package/@truffle/decoder) & [@truffle/codec](https://www.npmjs.com/package/@truffle/codec) which at time of writing are yet to be deprecated.

**Comment by ochikov** [comment]
Etherlime `2.3.5` is now supporting Node 12.
