### ISSUE TITLE
Proposal to add ethers.wallet() to current accounts objects in tests 

### ISSUE THREAD

**Issue by vsavovlime** [LimeChain/etherlime#51]
Currently accounts objects in tests contains private key and initial balance. It would be great if there is also ethers.Wallet().

**Benefits**
 - Easy way to get wallet address
 - Easy way to get wallet balance
 - Тhere will be no need to instance ethers.Wallet()

**Comment by Perseverance** [comment]
Thanks @vsavovlime I've added ethers.wallet() in the account object and updated the docs too. You can have this with version 0.9.1. I just published it, should be available very soon
